version: "3.8"
networks:     #docker networks
  net_frontend:
    external: true
  net_backend:
    external: true
services: 
  bot:        #discord bot to download torrents
    image: cameronoli/plex-bot:latest
    hostname: bot
    networks: 
      - net_frontend
    volumes:
      - /patriot/media-server/plex-bot/secrets/bot-tokens/prod:/usr/src/app/secrets/bot-tokens
  torrent:    #qbittorrent container
    image: linuxserver/qbittorrent
    hostname: torrent
    environment:
    #permissions
      - PUID=1000
      - PGID=1000
      - WEBUI_PORT=8080
    networks:
      - net_backend
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080/tcp
    volumes:
      - /patriot/media-server/config/qbit:/config
      - /data/torrents/:/data/torrents/
  plex:       #plex media server
    image: linuxserver/plex:latest
    hostname: plex
    deploy:
      resources:
        reservations:
          generic_resources:
            - discrete_resource_spec:
                kind: 'NVIDIA-GPU'
                value: 0
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
    networks: 
      - net_backend
    ports:
      - 32400:32400
    volumes:
      - /patriot/media-server/config/plex:/config
      - /data/media/:/data/media
  radarr:     #to handle movie subscriptions
    image: linuxserver/radarr
    hostname: radarr
    ports:
      - 7878:7878
    volumes:
      - /patriot/media-server/config/radarr:/config
      - /data/:/data
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
    networks:
      - net_frontend
      - net_backend
  sonarr:     #to handle series subscriptions
    image: linuxserver/sonarr
    hostname: sonarr
    ports:
      - 8989:8989
    volumes:
      - /patriot/media-server/config/sonarr:/config
      - /data/:/data
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
    networks:
      - net_frontend
      - net_backend
  bazarr:     #to handle subtitles
    image: linuxserver/bazarr
    hostname: bazarr
    ports:
      - 6767:6767
    volumes:
      - /patriot/media-server/config/bazarr:/config
      - /data/:/data
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
    networks:
      - net_frontend
      - net_backend
  overseerr:  #to handle user interaction of sonarr and radarr
    image: linuxserver/overseerr
    hostname: overseerr
    ports:
      - 5055:5055
    volumes:
      - /patriot/media-server/config/overseerr:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
    networks:
      - net_backend
      - net_frontend
  jackett:    #handles torrent indexes
    image: linuxserver/jackett
    hostname: jackett
    ports:
      - 9117:9117
    volumes:
      - /patriot/media-server/config/jackett:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
    networks:
      - net_backend
      - net_frontend
  sabnzbd:    #handles NZB downloads
    image: linuxserver/sabnzbd
    hostname: sabnzbd
    ports:
      - 7123:7123
    volumes:
      - /patriot/media-server/config/sabnzbd:/config
      - /data/usenet/:/data/usenet/
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
    networks:
      - net_frontend
  readarr:
    image: linuxserver/readarr:develop
    hostname: readarr
    networks:
      - net_frontend
      - net_backend
    ports:
      - 8787:8787
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
    volumes:
      - /patriot/media-server/config/readarr/config:/config
      - /data/:/data
  calibre-web:
    image: linuxserver/calibre-web
    hostname: calibre-web
    networks:
      - net_frontend
      - net_backend
    ports:
      - 8083:8083
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
    volumes:
      - /patriot/media-server/config/calibre-web/config:/config
      - /data/:/data