version: "3.8"
services: 
  bot:
    image: cameronoli/plex-bot:latest
    hostname: bot
    networks: 
      - frontend
    volumes:
      - ~/projects/plex-bot/secrets/bot-tokens:/usr/src/app/secrets/bot-tokens
  torrent:
    image: linuxserver/qbittorrent:latest
    hostname: torrent
    environment:
      - PUID=1000
      - PGID=1000
      - WEBUI_PORT=8080
    networks: 
      - frontend
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080/tcp
    volumes:
      - ~/projects/plex-bot-config/config/prod/qbit/config:/config
      - /disks/redTV/redmovies:/downloads/movies:Z
      - /disks/redTV/redtv:/downloads/tv:Z
  plex:
    image: linuxserver/plex:latest
    hostname: plex
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    networks: 
      - backend
    volumes:
      - ~/projects/plex-bot-config/config/prod/plex/config:/config
      - /disks/movies/movies:/movies/movies
      - /disks/redTV/redmovies:/movies/redmovies
      - /disks/redTV/redtv:/tv/redtv
      - /disks/movies/tv:/tv/bluetv
      - /disks/redTV/redmusic:/music/music
  proxy:
    image: jlesage/nginx-proxy-manager
    hostname: proxy
    ports:
      - 8090:8080
      - 8181:8181
      - 4443:4443
      - 22000:22000
    volumes:
      - ~/projects/plex-bot-config/config/prod/nginx:/config:rw
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
    networks:
      - frontend
      - backend
networks:
  frontend:
    driver: overlay
  backend:
    driver: overlay