version: "3.8"
services: 
  bot:
    image: localbot:v6 #cameronoli/plex-bot:0.1
    #networks: 
      #- frontend
    #depends_on: 
      #torrent:
        #condition: service_healthy
  torrent:
    image: linuxserver/qbittorrent:latest
    hostname: torrent
    environment:
      - PUID=1000
      - PGID=1000
      - WEBUI_PORT=8080
    #networks: 
      #- frontend
      #- test_backend
    #depends_on: 
      #- plex
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    volumes:
      #- /test/qbit/config:/config
      - /disks/movies/movies:/downloads
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8080"]
        interval: 10s
        timeout: 10s
        retries: 5
  plex:
    image: linuxserver/plex:latest
    hostname: plex
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM='claim-VsNs_W3mM7yAd4yyxULp'
    #networks: 
      #- backend
    ports: 
      - 32400:32400/tcp
    volumes:
      - /test/plex/config:/config
      - /disks/movies/movies:/movies
