version: "3.8"
services: 
  bot:
    image: cameronoli/plex-bot:0.1
    networks: 
      - host
    depends_on: torrent
    restart_policy: on-failure
  torrent:
    image: linuxserver/qbitottrent:latest
    networks: 
      - host
    depends_on: plex
    ports:
      - 14715:14715
    volumes:
      - media: #insert container path here
    restart_policy: on-failure
  plex:
    image: plexinc/pms-docker:latest
    networks: 
      - host
    ports: 
      - "32401:32401"
    volumes:
      - media: #insert container path here
    restart_policy: on-failure
volumes:
    media: