version: "3.9"
services: 
  bot:
    image: .
    #should I use an image stored in a git repo then use "build ."?
    container_name: discord
    volumes: 
      - 
    restart: unless-stopped
  torrent:
    image: linuxserver/qbitottrent:latest
    container_name: qbit
    volumes:
      -
    restart: unless-stopped
  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    ports: 
      - "32401:32401"
    volumes:
      -
    restart: unless-stopped
volumes:
    #I should probably use a LVM so my HDDs appear as a single folder