version: "3.9"
services: 
  bot:
    image: .
    container_name: discord
    volumes: 
      - 
    restart: unless-stopped
  torrent:
    image: linuxserver/qbitottrent:latest
    container_name: qbit
    volumes:
      -
    restart: unless-stopped
  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    volumes:
      -
    restart: unless-stopped
